export const ADD_ENTREES = 'ADD_ENTREES';
export const ENTREES_LOADING = 'ENTREES_LOADING';
export const ENTREES_FAILED = 'ENTREES_FAILED';

export const ADD_BIBIMBAPS = 'ADD_BIBIMBAPS';
export const BIBIMBAPS_LOADING = 'BIBIMBAPS_LOADING';
export const BIBIMBAPS_FAILED = 'BIBIMBAPS_FAILED';

export const ADD_STEWS = 'ADD_STEWS';
export const STEWS_LOADING = 'STEWS_LOADING';
export const STEWS_FAILED = 'STEWS_FAILED';

export const ADD_MISCITEMS = 'ADD_MISCITEMS';
export const MISCITEMS_LOADING = 'MISCITEMS_LOADING';
export const MISCITEMS_FAILED = 'MISCITEMS_FAILED';

export const ADD_SIDES = 'ADD_SIDES';
export const SIDES_LOADING = 'SIDES_LOADING';
export const SIDES_FAILED = 'SIDES_FAILED';